apiVersion: batch/v1
kind: Job
metadata:
  name: python-test-job
  labels:
    app: test
  annotations:
    "helm.sh/hook": test
    "argocd.argoproj.io/hook": PostSync
spec:
  template:
    metadata:
      name: python-test
      labels:
        app: test
    spec:
      containers:
        - name: wget
          image: nginx
          command: ["/bin/sh"]
          args: 
            - -c
            - |
              response=$(curl -s -o /dev/null -w "%{http_code},%{time_total},%{errormsg}" -m 5 http://{{ .Values.demoapp.service.name }}:{{ .Values.demoapp.service.port }}/insert/k1/v1)
              
              http_code=$(echo $response | cut -d',' -f1)
              time_total=$(echo $response | cut -d',' -f2)
              error_msg=$(echo $response | cut -d',' -f3)
              
              if [ -n "$error_msg" ]; then
                  echo "Error: $error_msg"
                  exit 1
              fi
              if [ $http_code -ne 200 ]; then
                  echo "Error: Unexpected HTTP status code: $http_code"
                  exit 1
              fi
              echo "Health check passed. Response time: ${time_total}s"
      restartPolicy: Never
  backoffLimit: 2