apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5zcmNtZXNoLmRldiI6eyJ1c2VybmFtZSI6InJvYm90X3JvYm90X3dvcmtzaG9wIiwicGFzc3dvcmQiOiJYWVBqUmhUSWRBV0xlRUMwd0lVc0o3YVA2bWlpN1dBbSIsImF1dGgiOiJjbTlpYjNSZmNtOWliM1JmZDI5eWEzTm9iM0E2V0ZsUWFsSm9WRWxrUVZkTVpVVkRNSGRKVlhOS04yRlFObTFwYVRkWFFXMD0ifX19
kind: Secret
metadata:
  creationTimestamp: "2023-10-21T07:09:48Z"
  name: pull-secret
  namespace: user-20
type: kubernetes.io/dockerconfigjson
