apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshopapp
spec:
  replicas: {{ .Values.workshopapp.replicaCount }}
  selector:
    matchLabels:
      app: workshopapp
  template:
    metadata:
      labels:
        app: workshopapp
    spec:
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 6 }}
      containers:
      - name: python
        image: {{ .Values.workshopapp.image }}
        env:
        {{- range $key, $value := .Values.workshopapp.extraEnv }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        - name: REDIS_HOST
          value: {{ .Values.workshopapp.redis.host }}
        - name: REDIS_PORT
          value: {{ .Values.workshopapp.redis.port }}
        ports:
        - containerPort: {{ .Values.workshopapp.service.port }}
---
{{- if .Values.workshopapp.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.workshopapp.service.name }}
spec:
  selector:
    app: workshopapp
  ports:
  {{- with .Values.workshopapp.service}}
  - port: {{ .port }}
    targetPort: {{ .targetPort }}
  {{- end}}
  type: ClusterIP
{{- end -}}
