apiVersion: v1
kind: Pod
metadata:
  name: python-test
  labels:
    app: test
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: nginx
      command: ["/bin/sh"]
      args: 
        - -c
        - |
          response=$(curl -s -o /dev/null -w "%{http_code}" http://{{ .Values.python.service.name}}:{{ .Values.python.service.port }}/insert/k1/v1)
          if [ $response -eq 500 ]; then
            echo "Server returned 500 error"
            exit 1
          else
            echo "Request successful"
            exit 0
          fi
  restartPolicy: Never
