on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      # clone source code
      - name: Checkout
        uses: actions/checkout@v3

      # registry login
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY }} -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # build and push image
      - name: Build and push
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/workshop/hahaha:0.0.1 hands-on/1-build-push-image/python-app
          docker push ${{ secrets.DOCKER_REGISTRY }}/workshop/hahaha:0.0.1

  image_scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.46.0
      - name: Scan Image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_REGISTRY }}
          trivy image ${{ secrets.DOCKER_REGISTRY }}/workshop/hahaha:0.0.1 --exit-code 132
